### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by AliKaramiFBK** [zhenpeiyang/MVS2D#15]
Hi guys, Thanks for your great work 
Would you please let me know what is the following error about ?
I did some search but I couldnt find the solution 
I would appresiate it if you could help 
thanks 

**Traceback (most recent call last):
  File "demo.py", line 72, in <module>
    outputs = model(imgs[0], imgs[1:], proj_mats[0], proj_mats[1:], inv_K_pool)
  File "/home/akarami/anaconda3/envs/mvs2d/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/akarami/mvs2d/networks/mvs2d.py", line 311, in forward
    src_imgs,
  File "/home/akarami/mvs2d/networks/mvs2d.py", line 230, in epipolar_fusion
    k, proj_mask, grid = homo_warping(k, src_proj, ref_proj,depth_values)
  File "/home/akarami/mvs2d/networks/module.py", line 72, in homo_warping
    proj = torch.matmul(src_proj, torch.inverse(ref_proj))
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.**

**Comment by zhenpeiyang** [comment]
Hi @AliKaramiFBK , what are the CUDA and pytorch version you are using?
